### PR TITLE
Add media submodule and update icons

### PR DESCRIPTION
**Pull request by brayo-pip**
This pull request adds a media submodule and updates the icons.

### CODE REVIEW

**Comment by ErikBjare** [comment]
Don't commit the derived icon images, they should be generated at build-time.

**Comment by brayo-pip** [comment]
Done!. I should probably add the icons folder to .gitignore too... if the changes are not meant to be committed.

**Comment by brayo-pip** [comment]
> Done!. I should probably add the icons folder to .gitignore too... if the changes are not meant to be committed.

I actually can't do that it would break the initial build process, since the icons are only generated if the tauri is called from the make file.

**Comment by brayo-pip** [comment]
I don't think there's an other commit to make. Merge?

**Comment by ErikBjare** [comment]
Thanks!

**Pull request merged**
